version: 2

updates:
  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
