version: "2"

linters:
  enable:
    - revive
  settings:
    revive:
      rules:
        - name: unused-parameter
          severity: error

formatters:
  enable:
    - gofmt
    - goimports
    - golines

  settings:
    goimports:
      local-prefixes:
        - "github.com/traPtitech/rucQ"
