services:
  mariadb:
    image: mariadb:11.8.2-noble
    ports:
      - "3306:3306"
    env_file:
      - ./.env
    healthcheck:
      test: mariadb-admin ping -h 127.0.0.1 -u root -p$$MARIADB_ROOT_PASSWORD
      interval: 1s
      timeout: 10s
      retries: 10

  swagger:
    image: swaggerapi/swagger-ui:v5.25.3
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /openapi/openapi.yaml
    volumes:
      - type: bind
        source: ./
        target: /openapi/

  adminer:
    image: adminer:5.3.0
    ports:
      - "8082:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    depends_on:
      - mariadb
