services:
  rucq:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_USER: root
      DB_PASSWORD: password
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_NAME: database
      RUCQ_DEBUG: "true"
      RUCQ_CORS_ALLOW_ORIGINS: "*"
    depends_on:
      mariadb:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: .

  mariadb:
    image: mariadb:11.8.2-noble
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: password
    healthcheck:
      test: mariadb-admin ping -h 127.0.0.1 -u root -p$$MARIADB_ROOT_PASSWORD
      interval: 1s
      timeout: 10s
      retries: 10

  swagger:
    image: swaggerapi/swagger-ui:v5.25.3
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /openapi/openapi.yaml
    volumes:
      - type: bind
        source: ./
        target: /openapi/

  adminer:
    image: adminer:5.3.0
    ports:
      - "8082:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    depends_on:
      mariadb:
        condition: service_healthy
