// Code generated by MockGen. DO NOT EDIT.
// Source: activity.go
//
// Generated by this command:
//
//	mockgen -source=activity.go -destination=mockactivity/activity.go -package=mockactivity
//

// Package mockactivity is a generated GoMock package.
package mockactivity

import (
	context "context"
	reflect "reflect"

	model "github.com/traPtitech/rucQ/model"
	activity "github.com/traPtitech/rucQ/service/activity"
	gomock "go.uber.org/mock/gomock"
)

// MockActivityService is a mock of ActivityService interface.
type MockActivityService struct {
	ctrl     *gomock.Controller
	recorder *MockActivityServiceMockRecorder
	isgomock struct{}
}

// MockActivityServiceMockRecorder is the mock recorder for MockActivityService.
type MockActivityServiceMockRecorder struct {
	mock *MockActivityService
}

// NewMockActivityService creates a new mock instance.
func NewMockActivityService(ctrl *gomock.Controller) *MockActivityService {
	mock := &MockActivityService{ctrl: ctrl}
	mock.recorder = &MockActivityServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActivityService) EXPECT() *MockActivityServiceMockRecorder {
	return m.recorder
}

// GetActivities mocks base method.
func (m *MockActivityService) GetActivities(ctx context.Context, campID uint, userID string) ([]activity.ActivityResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActivities", ctx, campID, userID)
	ret0, _ := ret[0].([]activity.ActivityResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActivities indicates an expected call of GetActivities.
func (mr *MockActivityServiceMockRecorder) GetActivities(ctx, campID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActivities", reflect.TypeOf((*MockActivityService)(nil).GetActivities), ctx, campID, userID)
}

// RecordPaymentAmountChanged mocks base method.
func (m *MockActivityService) RecordPaymentAmountChanged(ctx context.Context, payment model.Payment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordPaymentAmountChanged", ctx, payment)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordPaymentAmountChanged indicates an expected call of RecordPaymentAmountChanged.
func (mr *MockActivityServiceMockRecorder) RecordPaymentAmountChanged(ctx, payment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordPaymentAmountChanged", reflect.TypeOf((*MockActivityService)(nil).RecordPaymentAmountChanged), ctx, payment)
}

// RecordPaymentCreated mocks base method.
func (m *MockActivityService) RecordPaymentCreated(ctx context.Context, payment model.Payment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordPaymentCreated", ctx, payment)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordPaymentCreated indicates an expected call of RecordPaymentCreated.
func (mr *MockActivityServiceMockRecorder) RecordPaymentCreated(ctx, payment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordPaymentCreated", reflect.TypeOf((*MockActivityService)(nil).RecordPaymentCreated), ctx, payment)
}

// RecordPaymentPaidChanged mocks base method.
func (m *MockActivityService) RecordPaymentPaidChanged(ctx context.Context, payment model.Payment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordPaymentPaidChanged", ctx, payment)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordPaymentPaidChanged indicates an expected call of RecordPaymentPaidChanged.
func (mr *MockActivityServiceMockRecorder) RecordPaymentPaidChanged(ctx, payment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordPaymentPaidChanged", reflect.TypeOf((*MockActivityService)(nil).RecordPaymentPaidChanged), ctx, payment)
}

// RecordQuestionCreated mocks base method.
func (m *MockActivityService) RecordQuestionCreated(ctx context.Context, questionGroup model.QuestionGroup) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordQuestionCreated", ctx, questionGroup)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordQuestionCreated indicates an expected call of RecordQuestionCreated.
func (mr *MockActivityServiceMockRecorder) RecordQuestionCreated(ctx, questionGroup any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordQuestionCreated", reflect.TypeOf((*MockActivityService)(nil).RecordQuestionCreated), ctx, questionGroup)
}

// RecordRollCallCreated mocks base method.
func (m *MockActivityService) RecordRollCallCreated(ctx context.Context, rollCall model.RollCall) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordRollCallCreated", ctx, rollCall)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordRollCallCreated indicates an expected call of RecordRollCallCreated.
func (mr *MockActivityServiceMockRecorder) RecordRollCallCreated(ctx, rollCall any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordRollCallCreated", reflect.TypeOf((*MockActivityService)(nil).RecordRollCallCreated), ctx, rollCall)
}

// RecordRoomCreated mocks base method.
func (m *MockActivityService) RecordRoomCreated(ctx context.Context, room model.Room) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordRoomCreated", ctx, room)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordRoomCreated indicates an expected call of RecordRoomCreated.
func (mr *MockActivityServiceMockRecorder) RecordRoomCreated(ctx, room any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordRoomCreated", reflect.TypeOf((*MockActivityService)(nil).RecordRoomCreated), ctx, room)
}
