// Code generated by MockGen. DO NOT EDIT.
// Source: activity.go
//
// Generated by this command:
//
//	mockgen -source=activity.go -destination=mockrepository/activity.go -package=mockrepository
//

// Package mockrepository is a generated GoMock package.
package mockrepository

import (
	context "context"
	reflect "reflect"

	model "github.com/traPtitech/rucQ/model"
	gomock "go.uber.org/mock/gomock"
)

// MockActivityRepository is a mock of ActivityRepository interface.
type MockActivityRepository struct {
	ctrl     *gomock.Controller
	recorder *MockActivityRepositoryMockRecorder
	isgomock struct{}
}

// MockActivityRepositoryMockRecorder is the mock recorder for MockActivityRepository.
type MockActivityRepositoryMockRecorder struct {
	mock *MockActivityRepository
}

// NewMockActivityRepository creates a new mock instance.
func NewMockActivityRepository(ctrl *gomock.Controller) *MockActivityRepository {
	mock := &MockActivityRepository{ctrl: ctrl}
	mock.recorder = &MockActivityRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActivityRepository) EXPECT() *MockActivityRepositoryMockRecorder {
	return m.recorder
}

// CreateActivity mocks base method.
func (m *MockActivityRepository) CreateActivity(ctx context.Context, activity *model.Activity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateActivity", ctx, activity)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateActivity indicates an expected call of CreateActivity.
func (mr *MockActivityRepositoryMockRecorder) CreateActivity(ctx, activity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateActivity", reflect.TypeOf((*MockActivityRepository)(nil).CreateActivity), ctx, activity)
}

// GetActivitiesByCampID mocks base method.
func (m *MockActivityRepository) GetActivitiesByCampID(ctx context.Context, campID uint) ([]model.Activity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActivitiesByCampID", ctx, campID)
	ret0, _ := ret[0].([]model.Activity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActivitiesByCampID indicates an expected call of GetActivitiesByCampID.
func (mr *MockActivityRepositoryMockRecorder) GetActivitiesByCampID(ctx, campID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActivitiesByCampID", reflect.TypeOf((*MockActivityRepository)(nil).GetActivitiesByCampID), ctx, campID)
}
