// Code generated by MockGen. DO NOT EDIT.
// Source: room_status.go
//
// Generated by this command:
//
//	mockgen -source=room_status.go -destination=mockrepository/room_status.go -package=mockrepository
//

// Package mockrepository is a generated GoMock package.
package mockrepository

import (
	context "context"
	reflect "reflect"

	model "github.com/traPtitech/rucQ/model"
	gomock "go.uber.org/mock/gomock"
)

// MockRoomStatusRepository is a mock of RoomStatusRepository interface.
type MockRoomStatusRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoomStatusRepositoryMockRecorder
	isgomock struct{}
}

// MockRoomStatusRepositoryMockRecorder is the mock recorder for MockRoomStatusRepository.
type MockRoomStatusRepositoryMockRecorder struct {
	mock *MockRoomStatusRepository
}

// NewMockRoomStatusRepository creates a new mock instance.
func NewMockRoomStatusRepository(ctrl *gomock.Controller) *MockRoomStatusRepository {
	mock := &MockRoomStatusRepository{ctrl: ctrl}
	mock.recorder = &MockRoomStatusRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomStatusRepository) EXPECT() *MockRoomStatusRepositoryMockRecorder {
	return m.recorder
}

// GetRoomStatusLogs mocks base method.
func (m *MockRoomStatusRepository) GetRoomStatusLogs(ctx context.Context, roomID uint) ([]model.RoomStatusLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoomStatusLogs", ctx, roomID)
	ret0, _ := ret[0].([]model.RoomStatusLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoomStatusLogs indicates an expected call of GetRoomStatusLogs.
func (mr *MockRoomStatusRepositoryMockRecorder) GetRoomStatusLogs(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoomStatusLogs", reflect.TypeOf((*MockRoomStatusRepository)(nil).GetRoomStatusLogs), ctx, roomID)
}

// SetRoomStatus mocks base method.
func (m *MockRoomStatusRepository) SetRoomStatus(ctx context.Context, roomID uint, status *model.RoomStatus, operatorID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRoomStatus", ctx, roomID, status, operatorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRoomStatus indicates an expected call of SetRoomStatus.
func (mr *MockRoomStatusRepositoryMockRecorder) SetRoomStatus(ctx, roomID, status, operatorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRoomStatus", reflect.TypeOf((*MockRoomStatusRepository)(nil).SetRoomStatus), ctx, roomID, status, operatorID)
}
