// Code generated by MockGen. DO NOT EDIT.
// Source: notification.go
//
// Generated by this command:
//
//	mockgen -source=notification.go -destination=mockservice/notification.go -package=mockservice
//

// Package mockservice is a generated GoMock package.
package mockservice

import (
	context "context"
	reflect "reflect"

	model "github.com/traPtitech/rucQ/model"
	gomock "go.uber.org/mock/gomock"
)

// MockNotificationService is a mock of NotificationService interface.
type MockNotificationService struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationServiceMockRecorder
	isgomock struct{}
}

// MockNotificationServiceMockRecorder is the mock recorder for MockNotificationService.
type MockNotificationServiceMockRecorder struct {
	mock *MockNotificationService
}

// NewMockNotificationService creates a new mock instance.
func NewMockNotificationService(ctrl *gomock.Controller) *MockNotificationService {
	mock := &MockNotificationService{ctrl: ctrl}
	mock.recorder = &MockNotificationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationService) EXPECT() *MockNotificationServiceMockRecorder {
	return m.recorder
}

// SendAnswerChangeMessage mocks base method.
func (m *MockNotificationService) SendAnswerChangeMessage(ctx context.Context, editorUserID string, oldAnswer *model.Answer, newAnswer model.Answer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendAnswerChangeMessage", ctx, editorUserID, oldAnswer, newAnswer)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendAnswerChangeMessage indicates an expected call of SendAnswerChangeMessage.
func (mr *MockNotificationServiceMockRecorder) SendAnswerChangeMessage(ctx, editorUserID, oldAnswer, newAnswer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAnswerChangeMessage", reflect.TypeOf((*MockNotificationService)(nil).SendAnswerChangeMessage), ctx, editorUserID, oldAnswer, newAnswer)
}
