// Code generated by MockGen. DO NOT EDIT.
// Source: answer.go
//
// Generated by this command:
//
//	mockgen -source=answer.go -destination=mock/answer.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/traPtitech/rucQ/model"
	repository "github.com/traPtitech/rucQ/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockAnswerRepository is a mock of AnswerRepository interface.
type MockAnswerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAnswerRepositoryMockRecorder
	isgomock struct{}
}

// MockAnswerRepositoryMockRecorder is the mock recorder for MockAnswerRepository.
type MockAnswerRepositoryMockRecorder struct {
	mock *MockAnswerRepository
}

// NewMockAnswerRepository creates a new mock instance.
func NewMockAnswerRepository(ctrl *gomock.Controller) *MockAnswerRepository {
	mock := &MockAnswerRepository{ctrl: ctrl}
	mock.recorder = &MockAnswerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnswerRepository) EXPECT() *MockAnswerRepositoryMockRecorder {
	return m.recorder
}

// CreateAnswer mocks base method.
func (m *MockAnswerRepository) CreateAnswer(ctx context.Context, answer *model.Answer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAnswer", ctx, answer)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAnswer indicates an expected call of CreateAnswer.
func (mr *MockAnswerRepositoryMockRecorder) CreateAnswer(ctx, answer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAnswer", reflect.TypeOf((*MockAnswerRepository)(nil).CreateAnswer), ctx, answer)
}

// CreateAnswers mocks base method.
func (m *MockAnswerRepository) CreateAnswers(ctx context.Context, answers *[]model.Answer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAnswers", ctx, answers)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAnswers indicates an expected call of CreateAnswers.
func (mr *MockAnswerRepositoryMockRecorder) CreateAnswers(ctx, answers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAnswers", reflect.TypeOf((*MockAnswerRepository)(nil).CreateAnswers), ctx, answers)
}

// GetAnswerByID mocks base method.
func (m *MockAnswerRepository) GetAnswerByID(ctx context.Context, id uint) (*model.Answer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAnswerByID", ctx, id)
	ret0, _ := ret[0].(*model.Answer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAnswerByID indicates an expected call of GetAnswerByID.
func (mr *MockAnswerRepositoryMockRecorder) GetAnswerByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAnswerByID", reflect.TypeOf((*MockAnswerRepository)(nil).GetAnswerByID), ctx, id)
}

// GetAnswers mocks base method.
func (m *MockAnswerRepository) GetAnswers(ctx context.Context, query repository.GetAnswersQuery) ([]model.Answer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAnswers", ctx, query)
	ret0, _ := ret[0].([]model.Answer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAnswers indicates an expected call of GetAnswers.
func (mr *MockAnswerRepositoryMockRecorder) GetAnswers(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAnswers", reflect.TypeOf((*MockAnswerRepository)(nil).GetAnswers), ctx, query)
}

// UpdateAnswer mocks base method.
func (m *MockAnswerRepository) UpdateAnswer(ctx context.Context, answerID uint, answer *model.Answer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAnswer", ctx, answerID, answer)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAnswer indicates an expected call of UpdateAnswer.
func (mr *MockAnswerRepositoryMockRecorder) UpdateAnswer(ctx, answerID, answer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAnswer", reflect.TypeOf((*MockAnswerRepository)(nil).UpdateAnswer), ctx, answerID, answer)
}
