name: Renovate

on:
  push:
    branches:
      # Renovateに自動でrebaseさせるため
      - main

  schedule:
    # セキュリティ系のアップデートを確認するため毎日実行する
    - cron: "0 2 * * *"

  workflow_dispatch:
    inputs:
      debug:
        description: Enable debug logging
        type: boolean
        default: false
      dry_run:
        description: Run in dry-run mode
        type: boolean
        default: true

concurrency:
  group: renovate
  cancel-in-progress: true

jobs:
  renovate:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9f698171ed81b15d1823a05fc7211befd50c8ae0 # v6.0.3

      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: generate-token
        with:
          app-id: ${{ secrets.RENOVATE_APP_ID }}
          private-key: ${{ secrets.RENOVATE_APP_PRIVATE_KEY }}

      - uses: renovatebot/github-action@68a3ea99af6ad249940b5a9fdf44fc6d7f14378b # v46.1.6
        with:
          configurationFile: .github/renovate-bot.json5
          token: ${{ steps.generate-token.outputs.token }}
        env:
          LOG_LEVEL: ${{ inputs.debug && 'debug' || 'info' }}
          RENOVATE_DRY_RUN: ${{ inputs.dry_run && 'full' || '' }}
