name: Renovate

on:
  push:
    branches:
      # Renovateに自動でrebaseさせるため
      - main

  schedule:
    # RenovateがPRを作成できるのは1日の午前0時から4時までなので（schedule:monthly）、
    # 毎月1日の午前2時に実行する
    - cron: "0 2 1 * *"

  workflow_dispatch:
    inputs:
      debug:
        description: Enable debug logging
        type: boolean
        default: false
      dry_run:
        description: Run in dry-run mode
        type: boolean
        default: true

concurrency:
  group: renovate
  cancel-in-progress: true

jobs:
  renovate:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/create-github-app-token@v3
        id: generate-token
        with:
          app-id: ${{ secrets.RENOVATE_APP_ID }}
          private-key: ${{ secrets.RENOVATE_APP_PRIVATE_KEY }}

      - uses: renovatebot/github-action@68a3ea99af6ad249940b5a9fdf44fc6d7f14378b # v46.1.6
        with:
          configurationFile: .github/renovate-bot.json5
          token: ${{ steps.generate-token.outputs.token }}
        env:
          LOG_LEVEL: ${{ inputs.debug && 'debug' || 'info' }}
          RENOVATE_DRY_RUN: ${{ inputs.dry_run && 'full' || '' }}
